# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{liquidplanner}
  s.version = "0.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Brett Bender", "Adam Sanderson", "Mark Holton"]
  s.date = %q{2012-06-22}
  s.description = %q{LiquidPlanner API client, using ActiveResource}
  s.email = %q{api@liquidplanner.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "HISTORY",
    "README.rdoc",
    "Rakefile",
    "examples/README",
    "examples/create_task.rb",
    "examples/list_custom_fields.rb",
    "examples/list_tasks.rb",
    "examples/post-commit.rb",
    "examples/support/helper.rb",
    "examples/svn-post-commit.sh",
    "examples/track_time.rb",
    "examples/update_custom_field_value.rb",
    "lib/liquidplanner.rb",
    "lib/liquidplanner/base.rb",
    "lib/liquidplanner/debug.rb",
    "lib/liquidplanner/ext/connection.rb",
    "lib/liquidplanner/ext/exceptions.rb",
    "lib/liquidplanner/ext/hash.rb",
    "lib/liquidplanner/liquidplanner_resource.rb",
    "lib/liquidplanner/resources/account.rb",
    "lib/liquidplanner/resources/activity.rb",
    "lib/liquidplanner/resources/client.rb",
    "lib/liquidplanner/resources/comment.rb",
    "lib/liquidplanner/resources/container.rb",
    "lib/liquidplanner/resources/custom_field.rb",
    "lib/liquidplanner/resources/document.rb",
    "lib/liquidplanner/resources/estimate.rb",
    "lib/liquidplanner/resources/event.rb",
    "lib/liquidplanner/resources/folder.rb",
    "lib/liquidplanner/resources/leaf.rb",
    "lib/liquidplanner/resources/link.rb",
    "lib/liquidplanner/resources/luggage.rb",
    "lib/liquidplanner/resources/member.rb",
    "lib/liquidplanner/resources/milestone.rb",
    "lib/liquidplanner/resources/movable.rb",
    "lib/liquidplanner/resources/move_or_package.rb",
    "lib/liquidplanner/resources/note.rb",
    "lib/liquidplanner/resources/package.rb",
    "lib/liquidplanner/resources/packageable.rb",
    "lib/liquidplanner/resources/project.rb",
    "lib/liquidplanner/resources/root.rb",
    "lib/liquidplanner/resources/snapshot.rb",
    "lib/liquidplanner/resources/task.rb",
    "lib/liquidplanner/resources/treeitem.rb",
    "lib/liquidplanner/resources/workspace.rb",
    "lib/liquidplanner/resources/workspace_resource.rb",
    "test/liquidplanner_resource_test.rb",
    "test/workspace_test.rb"
  ]
  s.homepage = %q{http://github.com/liquidplanner/liquidplanner}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{LiquidPlanner API client}
  s.test_files = ["test/liquidplanner_resource_test.rb", "test/workspace_test.rb"]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activeresource>, [">= 3.0.0", "~> 3.0.0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 3.0.0", "~> 3.0.0"])
      s.add_runtime_dependency(%q<multipart-post>, [">= 1.0.1", "~> 1.0.1"])
      s.add_development_dependency(%q<highline>, [">= 1.5"])
      s.add_development_dependency(%q<mocha>, ["= 0.9.8"])
    else
      s.add_dependency(%q<activeresource>, [">= 3.0.0", "~> 3.0.0"])
      s.add_dependency(%q<activesupport>, [">= 3.0.0", "~> 3.0.0"])
      s.add_dependency(%q<multipart-post>, [">= 1.0.1", "~> 1.0.1"])
      s.add_dependency(%q<highline>, [">= 1.5"])
      s.add_dependency(%q<mocha>, ["= 0.9.8"])
    end
  else
    s.add_dependency(%q<activeresource>, [">= 3.0.0", "~> 3.0.0"])
    s.add_dependency(%q<activesupport>, [">= 3.0.0", "~> 3.0.0"])
    s.add_dependency(%q<multipart-post>, [">= 1.0.1", "~> 1.0.1"])
    s.add_dependency(%q<highline>, [">= 1.5"])
    s.add_dependency(%q<mocha>, ["= 0.9.8"])
  end
end

